---
# this config file is used for the docker container.
# use the contents of the config.yml.example file to configure a native installation.

# loop config
loop_freq: <%= ENV["LOOP_FREQ"] || 45 %>

# Proton
proton_gateway: <%= ENV["PROTON_GATEWAY"] || 10.2.0.1 %>

# OPNsense
opnsense_interface_addr: <%= ENV["OPN_INTERFACE_ADDR"] %>
opnsense_api_key: <%= ENV["OPN_API_KEY"] %>
opnsense_api_secret: <%= ENV["OPN_API_SECRET"] %>
opnsense_alias_name: <%= ENV["OPN_PROTON_ALIAS_NAME"] %>

# qBit
qbit_addr: <%= ENV["QBIT_ADDR"] %>
qbit_user: <%= ENV["QBIT_USER"] %>
qbit_pass: <%= ENV["QBIT_PASS"] %>
