services:
  qbop:
    image: ghcr.io/clajiness/qbop
    container_name: qbop
    restart: unless-stopped
    volumes:
      - log:/opt/qbop/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
    # This value determines how often the script runs. The default is 45 seconds. This value is recommended by ProtonVPN.
      - QBOP_JOB_FREQ=
    # The number of loops with a new forwarded port before updating OPNsense and qBit. The default is 3, min is 1, and max is 10.
      - REQUIRED_ATTEMPTS=
    # Default is `10.2.0.1`. Do not use http(s):// or a trailing slash.
      - PROTON_GATEWAY=
    # OPNsense Interface Address. Requires http(s):// and no trailing slash.
      - OPN_INTERFACE_ADDR=
    # OPNsense API Key
      - OPN_API_KEY=
    # OPNsense API Secret
      - OPN_API_SECRET=
    # The firewall alias that you use for ProtonVPN's forwarded port. For example, `proton_vpn_forwarded_port`.
      - OPN_PROTON_ALIAS_NAME=
    # [`true`/`false`] Skip qBittorrent. If `true`, subsequent qBit environment variables are not required.
      - QBIT_SKIP=
    # The IP address of your qBittorrent app. Requires http(s):// and no trailing slash.
      - QBIT_ADDR=
    # qBittorrent username
      - QBIT_USER=
    # qBittorrent password
      - QBIT_PASS=

volumes:
  log:
