services:
  qbop:
    image: ghcr.io/clajiness/qbop:latest
    container_name: qbop
    restart: unless-stopped
    ports:
      - "4567:4567"
    volumes:
      - data:/opt/qbop/data/
      - log:/opt/qbop/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # environment variables are documented here: https://github.com/clajiness/qbop?tab=readme-ov-file#env-variables
    environment:
      - UI_MODE=
      - LOOP_FREQ=
      - REQUIRED_ATTEMPTS=
      - PROTON_GATEWAY=
      - OPN_SKIP=
      - OPN_INTERFACE_ADDR=
      - OPN_API_KEY=
      - OPN_API_SECRET=
      - OPN_PROTON_ALIAS_NAME=
      - QBIT_SKIP=
      - QBIT_ADDR=
      - QBIT_USER=
      - QBIT_PASS=
      - LOG_LINES=
      - LOG_REVERSE=

volumes:
  data:
  log:
